version: "3.2"

services:
  mongo:
    image: mongo
    command: --quiet
    restart: always
    networks:
      - jasenrekisteri
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "/usr/local/wait-for-it.sh mongo:27017 && npm run create-defaults && npm start && npm run log"
    ports:
      - 3001:3001
    networks:
      - jasenrekisteri
    depends_on:
      - mongo
    environment:
      - MONGOURL=mongodb://mongo:27017/jasenrekisteri

volumes:
  db-data:
networks:
  jasenrekisteri:
