version: "3.2"

services:
  mongo:
    image: mongo
    restart: always
    networks:
      - jasenrekisteri
    volumes:
      - db-data:/data/db
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "/usr/local/wait-for-it.sh mongo:27017 && npm run create-defaults && npm run watch"
    env_file:
      - .env
    ports:
      - 3001:3001
    networks:
      - jasenrekisteri
    depends_on:
      - mongo
    environment:
      - MONGOURL='mongodb://mongo:27017/jasenrekisteri'

volumes:
  db-data:
networks:
  jasenrekisteri:
